# Generated by Django 4.0.4 on 2022-05-30 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://hcue.restaurant/assets/img/item/placeholder.jpg?v=1', max_length=500),
        ),
    ]
